### ISSUE TITLE
Save theme not FM

### ISSUE THREAD

**Issue by jimmymcperson** [JeidoUran/eox_fm_mod#1]
The save theme is not fm from what I can tell.

**Comment by JeidoUran** [comment]
Hey, sorry for the very very late answer, I never got any notification for your report.

Sadly, the save theme is actually a sound effect and not a music, and sound effects uses a different format than music, and are all stored within a single file, unlike musics. I actually tried to replace it back when I was working on the mod but I couldn’t open the sound effects file at all, so I gave up.

I don’t know if any progress was done in that regard since then, so I’ll have a look to see if it’s now possible to edit that, otherwise, I’ll have to leave it as is.

**Comment by JeidoUran** [comment]
After checking, I sadly don't think it's possible to edit that, or at least, not easily for now. Closing the issue, I'll re-open it whenever I find a way to fix that. Thanks for the report!
